### ISSUE TITLE
Parser fails with multi-term-expression containing scientific notation in v2

### ISSUE THREAD

**Issue by daschw** [ait-energy/IESopt.jl#35]
Consider the following MWE:

```yaml
config:
  optimization:
    problem_type: LP
    snapshots:
      count: 1
    solver:
      name: highs

carriers:
  electricity: {}

components:
  electricity_node:
    type: Node
    carrier: electricity

  electricity_market:
    type: Profile
    carrier: electricity
    node_to: electricity_node
    cost: 50
    mode: ranged

  electricity_demand:
    type: Profile
    carrier: electricity
    node_from: electricity_node
    value: 1e-6 * 7
```

This fails due to the last line. It used to work with IESopt@v1. Here's the error message.

```julia
┌ Error: Error(s) during model generation
│   debug = "electricity_demand"
│   number_of_errors = 1
│    = = = = = = = = = [ Error #1 ] = = = = = = = = =
│    ParseError:
│    # Error @ line 1:1
│    └ ── premature end of input
│    Stacktrace:
│      [1] _parse(rule::Symbol, need_eof::Bool, ::Type{Expr}, text::String, index::Int64; version::VersionNumber, ignore_trivia::Bool, filename::Nothing, first_line::Int64, ignore_errors::Bool, ignore_warnings::Bool, kws::@Kwargs{})
│        @ JuliaSyntax C:\Users\SchwabenederD\.julia\packages\JuliaSyntax\BHOG8\src\parser_api.jl:93
│      [2] _string_to_fevalexpr(str::AbstractString)
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\core\expression.jl:17
│      [3] _convert_to_expression(model::JuMP.Model, data::AbstractString)
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\core\expression.jl:177
│      [4] _parse_components!(model::JuMP.Model, description::Dict{String, Any})
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\parser.jl:350
│      [5] (::IESopt.var"#331#333"{JuMP.Model, String})()
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\parser.jl:63
│      [6] _parse_model!(model::JuMP.Model, filename::String, global_parameters::Dict)
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\parser.jl:16
│      [7] parse!(model::JuMP.Model, filename::AbstractString; parameters::Union{Nothing, Dict}, config::Union{Nothing, Dict}, addons::Union{Nothing, Dict}, carriers::Union{Nothing, Dict}, 
components::Union{Nothing, Dict}, load_components::Union{Nothing, Dict})
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\IESopt.jl:513
│      [8] generate!(model::JuMP.Model, filename::String; parameters::Union{Nothing, Dict}, config::Union{Nothing, Dict}, addons::Union{Nothing, Dict}, carriers::Union{Nothing, Dict}, components::Union{Nothing, Dict}, load_components::Union{Nothing, Dict}, skip_validation::Bool)
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\IESopt.jl:301
│      [9] generate!(filename::String)
│        @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\IESopt.jl:238
│     [10] pyjlany_call(self::typeof(IESopt.generate!), args_::Py, kwargs_::Py)
│        @ PythonCall.JlWrap C:\Users\SchwabenederD\.julia\packages\PythonCall\Nr75f\src\JlWrap\any.jl:43
│     [11] _pyjl_callmethod(f::Any, self_::Ptr{PythonCall.C.PyObject}, args_::Ptr{PythonCall.C.PyObject}, nargs::Int64)
│        @ PythonCall.JlWrap C:\Users\SchwabenederD\.julia\packages\PythonCall\Nr75f\src\JlWrap\base.jl:73
│     [12] _pyjl_callmethod(o::Ptr{PythonCall.C.PyObject}, args::Ptr{PythonCall.C.PyObject})
│        @ PythonCall.JlWrap.Cjl C:\Users\SchwabenederD\.julia\packages\PythonCall\Nr75f\src\JlWrap\C.jl:63
└ @ IESopt C:\Users\SchwabenederD\.julia\packages\IESopt\5VjfW\src\IESopt.jl:355
```

Changing the last line to `value: 7e-7` (single-term expression) or `value: 7 / 1000000` (no scientific notation) both work.
