### ISSUE TITLE
[Bug] Failing to parse correct component name in expression for a Decision in a template

### ISSUE THREAD

**Issue by daschw** [ait-energy/IESopt.jl#38]
Consider the following minimal IESopt config:
```yaml
config:
  optimization:
    problem_type: LP
    snapshots:
      count: 1
    solver:
      name: highs
  paths:
    templates: templates

carriers:
  electricity: {}

components:
  electricity_node:
    type: Node
    carrier: electricity

  electricity_demand:
    type: Profile
    carrier: electricity
    node_from: electricity_node
    value: 1

  electricity_supply:
    type: Supplier
    node_to: electricity_node
    cost: 1
```
with the following template in `templates/Supplier.iesopt.template.yaml`
```yaml
parameters:
  cost: ~
  node_to: ~

components:
  supply:
    type: Profile
    carrier: electricity
    mode: ranged
    ub: <self>.size:value
    node_to: <node_to>
  size:
    type: Decision
    cost: <cost>
```
Running this errors with
```julia
...
┌ error @ utils|utils ~     Trying to access unknown component
│   component_name = "size"
│   trigger = get_component(model::JuMP.Model, component_name::AbstractString) at IESopt.jl:741
│   origin = _finalize(e::Expression) at expression.jl:376
│   inside = _after_construct_variables!(profile::Profile) at profile.jl:255
│   debug = "electricity_supply.supply :: _after_construct_variables!"
└ @ IESopt src\utils\utils.jl:14
┌ Error: Error(s) during model generation
│   debug = "electricity_supply.supply :: _after_construct_variables!"
│   number_of_errors = 1
│    = = = = = = = = = [ Error #1 ] = = = = = = = = =
│    Trying to access unknown component
│    Stacktrace:
│      [1] get_component(model::JuMP.Model, component_name::AbstractString)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:745
│      [2] _finalize(e::Expression)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\core\expression.jl:376
│      [3] _after_construct_variables!(profile::Profile)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\core\profile.jl:255
│      [4] (::IESopt.var"#398#400"{JuMP.Model, typeof(IESopt._after_construct_variables!)})(component::Profile)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:63
│      [5] (::ProgressMeter.var"#46#49"{Distributed.RemoteChannel{Channel{Bool}}, IESopt.var"#398#400"{JuMP.Model, typeof(IESopt._after_construct_variables!)}})(x::Profile)
│        @ ProgressMeter C:\Users\SchwabenederD\.julia\packages\ProgressMeter\kVZZH\src\ProgressMeter.jl:1050
│      [6] progress_map(::Function, ::Vararg{Any}; mapfun::typeof(foreach), progress::ProgressMeter.Progress, channel_bufflen::Int64, kwargs::@Kwargs{})
│        @ ProgressMeter C:\Users\SchwabenederD\.julia\packages\ProgressMeter\kVZZH\src\ProgressMeter.jl:1041
│      [7] _build_model!(model::JuMP.Model)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:56
│      [8] build!(model::JuMP.Model)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:549
│      [9] (::IESopt.var"#405#407"{JuMP.Model})()
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:307
│     [10] generate!(model::JuMP.Model, filename::String; parameters::Union{Nothing, Dict}, config::Union{Nothing, Dict}, addons::Union{Nothing, Dict}, carriers::Union{Nothing, Dict}, components::Union{Nothing, Dict}, load_components::Union{Nothing, Dict}, skip_validation::Bool)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:302
│     [11] run(filename::String; parameters::Union{Nothing, Dict}, config::Union{Nothing, Dict}, addons::Union{Nothing, Dict}, carriers::Union{Nothing, Dict}, components::Union{Nothing, Dict}, load_components::Union{Nothing, Dict}, skip_validation::Bool)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:208
│     [12] run(filename::String)
│        @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:196
└ @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:355
┌ Error: Errors in model generation; skipping optimization
└ @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:211
```
As you can see, we try to find component name `size`, when we should actually look for `electricity_supply.size`

For reference, having this in a *plain* config without templates, like below, works fine.
```yaml
config:
  optimization:
    problem_type: LP
    snapshots:
      count: 1
    solver:
      name: highs
  paths:
    templates: templates

carriers:
  electricity: {}

components:
  electricity_node:
    type: Node
    carrier: electricity

  electricity_demand:
    type: Profile
    carrier: electricity
    node_from: electricity_node
    value: 1

  electricity_supply:
    type: Profile
    carrier: electricity
    mode: ranged
    ub: electricity_supply_size:value
    node_to: electricity_node

  electricity_supply_size:
    type: Decision
    cost: 1
```
