### ISSUE TITLE
Some Component parameters do not support "expressions"

### ISSUE THREAD

**Issue by sstroemer** [ait-energy/IESopt.jl#62]
Example: `Node` > `state_initial`

Should be able to support:

```yaml
store:
  type: Node
  state_initial: <battery_soc_t0> * <battery_e>
```

But currently requires:

```yaml
store:
  type: Node
  state_initial: <battery_energy_content_t0>
```
