### ISSUE TITLE
`finalize` function in templates not working with JuMP macros

### ISSUE THREAD

**Issue by daschw** [ait-energy/IESopt.jl#76]
I suppose the idea of the `finalize` function in templates is to also allow adding additional constraints etc. (see point 3 [here](https://github.com/ait-energy/IESopt.jl/blob/main/docs/src/pages/tutorials/templates_1.md#optional-parameter-and-sizing-decision)).
However, I think this does not really work at the moment.
If I try to replace the [CHP addon](https://github.com/ait-energy/IESopt.jl/blob/main/assets/addons/CHP.jl) in our [CHP example](https://github.com/ait-energy/IESopt.jl/blob/main/assets/examples/20_chp.iesopt.yaml#L12-L13) with the following lines in the [CHP template](https://github.com/ait-energy/IESopt.jl/blob/main/assets/templates/CHP.iesopt.template.yaml) 

```yaml
...

  finalize: |
    model = this.model
    T = get_T(model)
    cm = this.get("power_ratio")
    cb = this.get("power_loss_ratio")
    p_max = this.get("p_max")
    @constraint(model, [t in T], cm * this.heat.exp.out_heat[t] <= this.power.exp.out_electricity[t])
    @constraint(model, [t in T], this.power.exp.out_electricity[t] <= p_max - cv * this.heat.exp.out_heat[t])

...
```
I get the following error

```julia
┌ Error: [generate] Error(s) during model generation
│   debug = "grid_electricity :: _construct_objective!"
│   number_of_errors = 1
│    = = = = = = = = = [ Error #1 ] = = = = = = = = =
│    The function body AST defined by this @generated function is not pure. This likely means it contains a closure, a comprehension or a generator.
│    Stacktrace:
│     [1] (::RuntimeGeneratedFunctions.RuntimeGeneratedFunction{(:__virtual__,), IESopt.var"#_RGF_ModTag", IESopt.var"#_RGF_ModTag", (0x21ea3912, 0x8ab7dfc6, 0xbf2cc269, 0xb6437d67, 0xd7a70dc1), Expr})(args::Virtual)
│       @ RuntimeGeneratedFunctions C:\Users\SchwabenederD\.julia\packages\RuntimeGeneratedFunctions\M9ZX8\src\RuntimeGeneratedFunctions.jl:150
│     [2] _build_model!(model::Model)
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:91
│     [3] build!(model::Model)
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:532
│     [4] (::IESopt.var"#439#441"{Bool, Model})()
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:284
│     [5] generate!(model::Model, filename::String; skip_validation::Bool, kwargs...)
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:276
│     [6] run(filename::String; kwargs...)
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:199
│     [7] run(filename::String)
│       @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:196
└ @ IESopt c:\Users\SchwabenederD\.julia\dev\IESopt\src\IESopt.jl:330
```

**Comment by sstroemer** [comment]
Does that also fail when using `JuMP. @constraint`?

**Comment by daschw** [comment]
Yes, I also tried that. It fails with the same error message.

**Comment by sstroemer** [comment]
So... the following is a workaround, which I assume could be fine for now to "port" stuff and quickly change that later on if we figure out what the problem is.

### Template

```yaml
parameters:
  p_max: null
  h_max: null
  power_ratio: 0.55
  power_loss_ratio: 0.20
  efficiency: 0.40
  fuel: gas
  fuel_co2_emission_factor: 0.2
  fuel_in: null
  power_out: null
  heat_out: null
  co2_out: null

functions:
  validate: |
    @check this.get("p_max") > 0
    @check this.get("h_max") > 0
    @check this.get("fuel_in") isa String
    @check this.get("power_out") isa String
    @check this.get("heat_out") isa String
    @check this.get("co2_out") isa String
    @check (this.get("p_max") - this.get("power_loss_ratio") * this.get("h_max") > 0)

  finalize: |
    model = this.model
    T = get_T(model)
    cm = this.get("power_ratio")
    cv = this.get("power_loss_ratio")
    p_max = this.get("p_max")
    for t in T
        @constraint(model, cm * this.heat.exp.out_heat[t] <= this.power.exp.out_electricity[t])
        @constraint(model, this.power.exp.out_electricity[t] <= p_max - cv * this.heat.exp.out_heat[t])
    end

components:
  power:
    type: Unit
    inputs: {<fuel>: <fuel_in>}
    outputs: {electricity: <power_out>, co2: <co2_out>}
    conversion: 1 <fuel> -> <efficiency> electricity + <fuel_co2_emission_factor> co2
    capacity: <p_max> out:electricity

  heat:
    type: Unit
    inputs: {<fuel>: <fuel_in>}
    outputs: {heat: <heat_out>, co2: <co2_out>}
    conversion: 1 <fuel> -> <efficiency>/<power_loss_ratio> heat + <fuel_co2_emission_factor> co2
    capacity: <h_max> out:heat
```

### Component

```yaml
# ...

  chp:
    type: CHP
    p_max: 10
    h_max: 10
    fuel_in: grid_gas
    power_out: grid_electricity
    heat_out: grid_heat
    co2_out: grid_co2
```
