### ISSUE TITLE
Allow structuring of global parameters

### ISSUE THREAD

**Issue by sstroemer** [ait-energy/IESopt.jl#81]
Implement:

```yaml
parameters:
  - global.param.iesopt.yaml
  - grid_fees.param.iesopt.yaml
```

**Comment by sstroemer** [comment]
Duplicate keys (one file overwriting a key that is already present in an earlier one) should "error" for safety reasons.

```yaml
config:
  general:
    parameter_mode: unique  # or `overwrite`
```

If `unique`, should `@critical` on duplicate, if `overwrite` then a previous value is overwritten by a later one.
